customer/api/urls.py
from django.urls import path
from customer.api import views


urlpatterns=[
    path("",views.index),

]

customer/urls.py
from django.urls import path,include
from customer import views,contest_views

app_name="customer"

urlpatterns=[
    path("",views.index,name="index"),
    path("categories",views.categories,name="categories"),
    path("send_celery_mail",views.send_celery_mail,name="send_celery_mail"),
    path("create-contest/<int:id>",views.create_contest,name="create_contest"),
    path("browse-contests", views.browse_contests, name="browse_contests"),
    path('create-contest/<str:contest>/<str:step>/',views.contest_step,name="contest_step"),
    path('edit-contest/<str:contest>/<str:step>/',contest_views.edit_contest,name="edit_contest"),
    path('edit-bc-contest/<str:contest>/<str:step>/',contest_views.bc_edit_contest,name="bc_edit_contest"),
    path('edit-wp-contest/<str:contest>/<str:step>/',contest_views.wp_edit_contest,name="wp_edit_contest"),
    path('edit-ba-contest/<str:contest>/<str:step>/',contest_views.ba_edit_contest,name="ba_edit_contest"),
    path('edit-et-contest/<str:contest>/<str:step>/',contest_views.et_edit_contest,name="et_edit_contest"),
    path('edit-sm-contest/<str:contest>/<str:step>/',contest_views.sm_edit_contest,name="sm_edit_contest"),
    path('edit-cn-contest/<str:contest>/<str:step>/',contest_views.cn_edit_contest,name="cn_edit_contest"),
    path('edit-ma-contest/<str:contest>/<str:step>/',contest_views.ma_edit_contest,name="ma_edit_contest"),
    path('edit-lp-contest/<str:contest>/<str:step>/',contest_views.lp_edit_contest,name="lp_edit_contest"),
    path('edit-td-contest/<str:contest>/<str:step>/',contest_views.td_edit_contest,name="td_edit_contest"),
    path('edit-md-contest/<str:contest>/<str:step>/',contest_views.md_edit_contest,name="md_edit_contest"),
    path('edit-bkc-contest/<str:contest>/<str:step>/',contest_views.bkc_edit_contest,name="bkc_edit_contest"),
    path('edit-mgc-contest/<str:contest>/<str:step>/',contest_views.mgc_edit_contest,name="mgc_edit_contest"),
    path('edit-wpd-contest/<str:contest>/<str:step>/',contest_views.wpd_edit_contest,name="wpd_edit_contest"),
    path('submit-contest/<str:contest>',views.submit_contest,name="submit_contest"),
    path('add-attachment/<str:contest>',views.add_attachment,name="add_attachment"),
    path('apply-discount/<str:contest>',views.apply_discount,name="apply_discount"),
    path('delete-attachment/<str:attach_id>',views.delete_attachment,name="delete_attachment"),
    path('draft-contest/<str:contest>',views.draft_contest,name="draft_contest"),
    path('decline-entry/<int:contest>/<int:entry>',views.decline_entry,name="decline_entry"),
    path('rate-entry/<int:contest>/<int:entry>',views.rate_entry,name="rate_entry"),
    path('confirm-finalists/<int:contest_id>',views.confirm_finalists,name="confirm_finalists"),
    path('confirm-winner/<int:contest_id>',views.confirm_winner,name="confirm_winner"),
    path('delete-contest/<int:contest_id>',contest_views.delete_contest,name="delete_contest"),
    path('add-announcement/<int:contest_id>',views.add_anouncement,name="add_anouns"),
    path('delete-announcement/<int:anouns_id>',views.delete_announcement,name="delete_anouns"),
    path('split-prize/<int:contest>',views.split_prize,name="split_prize"),
    path('split-prize-to-designers/<int:contest>',views.split_prize_to_designers,name="split_prize_to_designers"),
    path('invoice/<int:invoice>',views.invoice,name="invoice"),
    path('start_poll/<int:contest>',views.start_poll,name="start_poll"),
    path('poll/<int:poll>/edit',views.edit_poll,name="edit_poll"),
    path('poll/<poll>',views.poll_detail,name="poll_detail"),
    path('poll/<int:poll>/delete',views.delete_poll,name="delete_poll"),
    path('poll_obj/<int:poll_obj>/add_comment',views.add_poll_comment,name="add_poll_comment"),
    path('poll_obj/<int:poll_comment>/delete_comment',views.delete_comment,name="delete_comment"),
    path('teams',views.teams,name="teams"),
    path('invite-designer/<str:user>/<int:contest>',views.invite_designer,name="invite_designer")

]

designer/urls.py
from django.urls import path
from designer import views

app_name="designer"

urlpatterns=[
    path("",views.index,name="index"),
    path("browse-contests",views.browse_contests,name="browse_contests"),
    path("get_by_filter",views.get_by_filter,name="get_by_filter"),
    path("submit_design/<int:contest_id>", views.submit_design, name="submit_design"),
    path("submit-final-design/<int:contest_id>", views.submit_final_design, name="submit_final_design"),
    path("submit-final-works/<int:contest_id>/<int:entry_id>", views.submit_final_works, name="submit_final_works"),
    path("delete-final-work/<int:contest_id>/<int:work_id>", views.delete_final_work, name="delete_final_work"),
    path("approve-files/<int:contest_id>", views.approve_files, name="approve_files"),
    path("submit_all_files/<int:contest_id>", views.submit_all_files, name="submit_all_files"),
    path("delete-entry/<int:entry>",views.delete_entry,name="delete_entry")
]

home/urls.py
from django.urls import path, include
from home import views
from user import views as user_views

app_name = "home"

urlpatterns=[
    path("",views.index,name="index"),
    path("react",views.react,name="react"),
    path("get_by_filter", views.get_by_filter, name="get_by_filter"),
    path("contest/<int:contest_id>",views.contest,name="contest"),
    path("contest/<int:contest_id>/apply_filters",views.apply_filters,name="apply_filters"),
    path("entry/<int:contest_id>/<int:entry_id>",views.entry_detail,name="entry_detail"),
    path("add_comment/<int:contest_id>/<int:entry_id>",views.add_comment,name="add_comment"),
    path("delete_comment/<int:comment_id>",views.delete_comment,name="delete_comment"),
    path("edit_comment/<int:comment_id>",views.edit_comment,name="edit_comment"),
    path("create-payout-request/<str:user>",views.create_payout_request,name="create_payout_request"),
    path("nda/<int:contest_id>",views.nda,name="nda"),
    path("notifications/",views.notifications,name="notifications"),
    path("read_notifications/",views.read_notifications,name="read_notifications"),
    path("check_notifications/",views.check_notifications,name="check_notifications"),
    path("get_nots_list/",views.get_nots_list,name="get_nots_list"),
    path("submit-a-request/",views.submit_request,name="submit_request"),
    path("terms-of-use/",views.terms,name="terms"),
    path("privacy-policy/",views.privacy,name="privacy"),
    path("wallet/",views.wallet,name="wallet"),
    path('review/delete/<int:id>',views.delete_review,name="delete_review"),

    path("profile/<str:username>",user_views.public_profile,name="public_profile"),
    path("profile/<str:username>/about",user_views.profile_about,name="profile_about"),
    path('ref/<str:link>',views.refferal_link,name="refferal_link"),
    path('discover',views.discover,name="discover"),
    path('search',views.find_a_designer,name="find_a_designer"),





]

customer/forms.py
from django import  forms
from django_countries.data import COUNTRIES
from django_countries.fields import CountryField

from customer.models import Poll


class CountryForm(forms.Form):
    country = CountryField().formfield()
    def __init__(self,*args, **kwargs):

        super(CountryForm, self).__init__(*args, **kwargs)

        self.fields["country"].widget.attrs={'class':'form-control','name':'country'}
        self.fields["country"].required = True

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ["title","content"]

customer/api/views.py
import random
from datetime import timedelta

import django_filters
from django.db.models import Value, CharField, IntegerField, Count, Max, QuerySet
from django.http import HttpResponse
# from rest_framework.filters import OrderingFilter
from django.utils import timezone
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework_tricks.filters import OrderingFilter

from customer.api.paginations import ContestPagination
from customer.api.serializers import ContestSerializer, AllCategorySerializer
from customer.models import Contest, SubCategory
from user.api.permissions import IsAuthorized, IsCompleted


class ContestListAPIView(ListAPIView):
    serializer_class = ContestSerializer

    filter_backends = [OrderingFilter,django_filters.rest_framework.DjangoFilterBackend]
    filterset_fields = ('category','status','round','is_locked')
    pagination_class = ContestPagination

    def get_queryset(self):
        qs=Contest.objects.filter(is_paid=True,is_draft=False,is_temp=False)

        try :
            if self.request.GET["is_private"] == "true": qs = qs.filter(form_fields__is_private=True)
        except KeyError:
            pass
        try :
            if self.request.GET["is_hidden"] == "true": qs = qs.filter(form_fields__is_hidden=True)
        except KeyError:
            pass
        try :
            if self.request.GET["is_guaranteed"] == "true": qs = qs.filter(form_fields__is_guaranteed=True)
        except KeyError:
            pass

        try:
            min=self.request.GET["prize_min"]
            qs=qs.filter(prize__gt=min)
        except KeyError:
            pass

        try:
            max=self.request.GET["prize_max"]
            qs=qs.filter(prize__lt=max)
        except KeyError:
            pass

        try:
            if self.request.GET["ordering"] == "entry_count":
                qs = qs.annotate(entry_count=Count('entries')) \
                                .order_by('-entry_count')
            elif self.request.GET["ordering"] == "-entry_count":
                qs = qs.annotate(entry_count=Count('entries')) \
                                .order_by('entry_count')
        except KeyError:
            pass

        try:
            df=self.request.GET["days_left"]
            if df == "1":

                qs = qs.filter(finish_date__range=[timezone.now(),timezone.now() + timedelta(days=1)])
            if df == "2":

                qs = qs.filter(finish_date__range=[timezone.now() + timedelta(days=1),timezone.now() + timedelta(days=2)])

            if df == "3":

                qs = qs.filter(finish_date__range=[timezone.now() + timedelta(days=2),timezone.now() + timedelta(days=3)])

            if df == "4":

                qs = qs.filter(finish_date__gt=timezone.now() + timedelta(days=3))


        except KeyError:
            pass

        return qs



class ContestDetailAPIView(RetrieveAPIView):
    queryset = Contest.objects.all()
    serializer_class = ContestSerializer
    lookup_field = 'slug'
    permission_classes = [IsAuthorized,IsCompleted]

class AllCategoryListAPIView(ListAPIView):
    queryset = SubCategory.objects.all()
    serializer_class = AllCategorySerializer

templates/customer/categories.html
{% extends "customer/layout.html" %}
{% load static %}
{% block head %}
    <title>Categories / Zignative Crowdsourcing</title>
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <ol class="breadcrumb  mb-4 mt-2">
            <li class="breadcrumb-item ">Contests</li>
            <li class="breadcrumb-item active">Categories</li>
        </ol>
        <div class="container">
            <h3 class="jumbotron-heading text-center">What do you need designed?</h3>
            <div class="row d-flex justify-content-center">
                <div class="input-group col-lg-7 mb-3   rounded">
                    <input type="search" id="searchbar" onkeyup="liveSearch()" class="form-control rounded" placeholder="Search what you need to design"
                           aria-label="Search"
                           aria-describedby="search-addon"/>
                    <span class="input-group-text border-0" id="search-addon">
                <i class="fas fa-search"></i>
                </span>
                </div>
                {% for main_category in main_categories %}
                <div class="col-lg-6">
                    <div class="row category-group mt-4">
                        <div class="mt-2 mb-1 col-lg-10"><h6 >{{ main_category }} </h6></div>
                        {% for sub_category in main_category.sub_categories.all %}
                            <div class="col-lg-10  mt-1 category-item"><a href="
                        {% url "customer:create_contest" sub_category.id %}

                        ">{{ sub_category.title }}</a>
                            {% if sub_category.get_min_price %}
                                <span class="float-right">{{ sub_category.get_min_price.currency.symbol }}{{ sub_category.get_min_price_total|floatformat:-2  }}</span>

                            {% endif %}
                            </div>
                        {% endfor %}


                    </div>
                </div>
                {% endfor %}


            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static "dashboard/js/categories.js" %}"></script>
    <script>
    document.getElementById("nav_categories").style.backgroundColor ="#D2562C"
    document.getElementById("nav_categories").classList.replace("text-dark","text-white")

    </script>
{% endblock %}

templates/customer/index.html
{% extends "customer/layout.html" %}
{% load static %}
{% block head %}
<title>Dashboard | Zignative</title>
{% endblock %}

{% block body %}

<div class="container-fluid mt-5">

            {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                                    <div class="alert alert-danger " role="alert">

                {% else %}
                                    <div class="alert alert-{{ message.tags }} " role="alert">

                {% endif %}
            {{ message }}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
            </div>
            {% endfor %}
            {% endif %}

                </div>
                <div class="container">


                        <h3 class="jumbotron-heading text-center mb-4">Projects
                            {% if request.user.contests.count != 0 %}
                            <a href="{% url "customer:categories" %}" class="btn btn-success btn-sm float-right ">Create New Contest</a>
                            {% endif %}
                        </h3>





                    {% include "includes/dashboard/projects.html" with contests=contests %}
                </div>

{% endblock %}

{% block script %}
<script>
    document.getElementById("nav_your_contests").style.backgroundColor ="#D2562C"
    document.getElementById("nav_your_contests").classList.replace("text-dark","text-white")

    </script>
{% endblock %}

templates/customer/invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>invoice order receipt - Bootdey.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
       <style type="text/css">
body{margin-top:20px;
background:#eee;
}

.invoice {
    padding: 30px;
}

.invoice h2 {
	margin-top: 0px;
	line-height: 0.8em;
}

.invoice .small {
	font-weight: 300;
}

.invoice hr {
	margin-top: 10px;
	border-color: #ddd;
}

.invoice .table tr.line {
	border-bottom: 1px solid #ccc;
}

.invoice .table td {
	border: none;
}

.invoice .identity {
	margin-top: 10px;
	font-size: 1.1em;
	font-weight: 300;
}

.invoice .identity strong {
	font-weight: 600;
}


.grid {
    position: relative;
	width: 100%;
	background: #fff;
	color: #666666;
	border-radius: 2px;
	margin-bottom: 25px;
	box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.1);
}

</style>
</head>
<body>
<div class="container">
<div class="row">
    				<!-- BEGIN INVOICE -->
					<div class="col-xs-12">
						<div class="grid invoice">
							<div class="grid-body">
								<div class="invoice-title">
									<div class="row">
										<div class="col-xs-12">
											<img src="http://134.122.93.235/assets/images/Logo.svg" alt="" height="35">
										</div>
									</div>
									<br>
									<div class="row">
										<div class="col-xs-12">
											<h2>INVOICE
											<span class="small"> #{{ invoice.id }}</span></h2>
										</div>
									</div>
								</div>
								<hr>
								<div class="row">
									<div class="col-xs-6">
										<address>
											ZIGNATIVE S.R.L.
CIF: 42659750
Reg. com: J22/1304/2020
Address: Sat Valea Adanca Com. Miroslava, Str. Imasului, Nr.83, Camera 1, Et.2, Ap.27, Valea Adanca, Jud. Iasi
IBAN : RO70INGB0000999910403677
Bank: ING BANK NV
										</address>
									</div>
									<div class="col-xs-6 text-right">
										<address>
											<strong>Invoice To:</strong><br>
											{{ invoice.billing_json.name }}<br>
											{{ invoice.billing_json.address1 }} &nbsp;
											{{ invoice.billing_json.address2 }}<br>
											{{ invoice.billing_json.city }} |
											{{ invoice.billing_json.state }} {{ invoice.billing_json.zipcode }}<br>
                                            {{ invoice.billing_json.country}}<br>
										</address>
									</div>
								</div>
								<div class="row">
									<div class="col-xs-6">

									</div>
									<div class="col-xs-6 text-right">
										<address>
											<strong>Order Date:</strong><br>
                                            {{ invoice.created_date}}
										</address>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<h3>ORDER SUMMARY</h3>
										<table class="table table-striped">
											<thead>
												<tr class="line">
													<td><strong>#</strong></td>
													<td class="text-center"><strong>DESCRIPTION</strong></td>
													<td class="text-right"><strong></strong></td>
													<td class="text-right"><strong>QTY</strong></td>
													<td class="text-right"><strong>SUBTOTAL</strong></td>
												</tr>
											</thead>
											<tbody>
                                            {% for key, value in jsonfield.items %}

                                                <tr>
													<td>{{ key }}</td>
													<td><strong>{{ value.title }}</strong><br>{{ value.detail }}</td>
													<td class="text-center"></td>
													<td class="text-right">1</td>
                                                    {% if value.free %}
                                                        <td class="text-right"><del>${{ value.subtotal }}</del> Free</td>

                                                    {% else%}
                                                        <td class="text-right">${{ value.subtotal }}</td>

                                                    {% endif %}
												</tr>
                                            {% endfor %}



												<tr>
													<td colspan="3">
													</td><td class="text-right"><strong>Total</strong></td>
													<td class="text-right"><strong>${{ total }}</strong></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
								<div class="row">
								</div>
							</div>
						</div>
					</div>
					<!-- END INVOICE -->
				</div>
</div>



<script type="text/javascript">

</script>
</body>
</html>

templates/customer/poll_detail.html
{% extends "customer/layout.html" %}
{% load static %}
{% load customer_filters %}
{% block head %}
    <title>{{ poll.title }} | Zignative </title>
    <script src="https://use.fontawesome.com/5ac93d4ca8.js"></script>
    <style>

    </style>
    <script src="{% static "dashboard/js/star-rating.js" %}"></script>

{% endblock %}

{% block body %}

    <div class="container-fluid">
    <ol class="breadcrumb  mb-4 mt-2">
        <li class="breadcrumb-item ">
            {% if request.user.profile.role == "designer" %}
                <a href="{% url "designer:browse_contests" %}" class="step-link">Contests</a>
            {% else %}
                <a href="{% url "customer:browse_contests" %}" class="step-link">Contests</a>
            {% endif %}
        </li>
        <li class="breadcrumb-item active">
            <a href="{% url "home:contest" contest.id %}" class="step-link">{{ contest.title }}</a>

        </li>
    </ol>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == "error" %}
                <div class="alert alert-danger " role="alert">

            {% else %}
                <div class="alert alert-{{ message.tags }} " role="alert">

            {% endif %}
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endfor %}
    {% endif %}


<div class="mb-4">
    <div class="row">
        <div class="col-8">
            <h4 class="">Results for poll #{{ poll.id }}</h4>
            <span class="text-muted">{{ poll.poll_comments.count }} votes so far</span>
        </div>
       {% if request.user == poll.contest.user %}
        <div class="col-4 ">
            <label class for="">Share your poll</label>
            <div class="row">
                <input id="myInput" type="text" readonly value="{{ domain }}/customer/poll/{{ poll.uid }}" class="form-control col-8" >
                <button id="copy-button" onclick="copy()" class="btn-sm btn btn-success col-2">Copy</button>

            </div>
        </div>
       {% endif %}
    </div>

</div>

{% for obj in poll.entries.all %}
    <div class="row mb-4">
        <div class="col-lg-3 col-sm-12 col-md-12 mr-5">
            <span><span class="text-muted">#{{ obj.entry.id }} by</span> <a
                    href="{% url "home:public_profile" obj.entry.user %}"
                    class="step-link">{{ obj.entry.user }}</a></span> <br>
            <img src="{{ obj.entry.get_image }}" class="border" height="400" width="400" alt="">
            <hr>
            <div class="row ml-3">
                <div class="col-4 border-right">
                    <span class="h1 font-weight-bold">{{ obj.get_average_rating|floatformat:1 }}</span><br>
                    <span class="text-muted">average rating</span>
                </div>
                <div class="col-4 border-right">
                    <span class="h1 font-weight-bold">{{ obj.poll_comments.all.count }}</span><br>
                    <span class="text-muted">votes</span>
                </div>
            </div>
            {% for i in 6|ranger reversed %}
                <div class="row mt-3">
                    <div class="col-3">
                        <div class="row ml-4  " id="info_rate_{{ i }}_{{ obj.id }}"></div>
                    </div>
                    <div class="col-5 ml-4">
                        <div class="progress">

                            <div class="progress-bar bg-info" role="progressbar"
                                 aria-valuenow="{{ obj.id|get_obj_ratio:i }}"
                                 aria-valuemin="0" aria-valuemax="100" style="width:{{ obj.id|get_obj_ratio:i }}%">
                                {% if not obj.id|get_obj_count:i == 0 %}
                                    {{ obj.id|get_obj_count:i }}
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>

                <br>

            {% endfor %}

        </div>
        <div class="col-lg-8 col-sm-12 col-md-12 mt-4 ml-5">
            <div style="height: 500px; overflow: auto; overflow-x:hidden ">
                {% for comment in obj.poll_comments.all %}
                    <div class="row mb-5">

                        <div class="col-lg-1 col-sm-12">
                            <img class="img-rounded" width="65" height="65"
                                 src="{{ comment.user.profile.get_photo }}" alt="">


                        </div>
                        <div class="col-lg-8 col-sm-12">

                            <p class="mb-0"><i>"{{ comment.content }}"</i></p>

                            <div id="rating_{{ comment.id }}" class="mt-1">

                            </div>

                            <br>
                            <small class="text-muted">{{ comment.user }} - reviewed {{ comment.created_date|timesince }} ago</small>

                        </div>
                        <div class="col-1">

                            {% if comment.user == request.user %}
                            <a href="{% url "customer:delete_comment" comment.id %}"><i class="fa fa-trash"></i></a>
                            {% endif %}

                        </div>
                    </div>

                {% endfor %}
                {% if not obj.poll_comments.all %}
                    There is no vote for this entry
                {% endif %}
            </div>
            <form class="d-flex mt-5 flex-column " action="{% url "customer:add_poll_comment" obj.id %}" method="post"
                  pid="{{ obj.id }}" onsubmit="return validateForm(this)"
                  id="review_form">
                {% csrf_token %}

                <span class="text-danger" hidden id="warn_rate_{{ obj.id }}">Rating must be filled out</span>
                <div id="rating_f_{{ obj.id }}" class="h2">

                </div>

                <input type="number" name="rate" id="rate_input_{{ obj.id }}" hidden>
                {% csrf_token %}
                <div class="form-group">
                    <label for="feedback_textarea">Leave Review</label>
                    <textarea required class="form-control" id="review" name="review" rows="3"></textarea>
                </div>
                <button class="btn btn-success float-right">Submit</button>
            </form>
        </div>

    </div>
    <hr>
{% endfor %}




</div>

{% endblock %}

{% block script %}

    <script>
        {% for comment in poll.poll_comments.all %}
            raterJs({
                element: document.querySelector("#rating_{{ comment.id }}"),
                readOnly: true,
                rating: Number({{ comment.rate }}),

            });
        {% endfor %}
    </script>
    <script>
        {% for obj in poll.entries.all %}
            for (var i = 1; i < 6; i++) {
                raterJs({
                    element: document.querySelector(`#info_rate_${i}_{{ obj.id }}`),
                    readOnly: true,
                    rating: i,

                });

            }
            raterJs({
                element: document.querySelector(`#rating_f_{{ obj.id }}`),
                rateCallback: function rateCallback(rating, done) {
                    this.setRating(rating);
                    done();
                    document.getElementById("rate_input_{{ obj.id }}").value = rating
                }

            });
        {% endfor %}
        function validateForm(e) {
            var pid = e.getAttribute("pid")
            if (!document.getElementById("rate_input_" + pid).value) {
                document.getElementById("warn_rate_" + pid).hidden = false
                return false;
            }
        }


    function copy() {
            var copyText = document.getElementById("myInput");
            var copyButton = document.getElementById("copy-button")
            copyText.select();
            copyText.setSelectionRange(0, 99999)
            document.execCommand("copy");
            copyButton.innerHTML = "Copied"
        }
    </script>

{% endblock %}