customer/urls.py
from django.urls import path,include
from customer import views,contest_views

app_name="customer"

urlpatterns=[
    path("",views.index,name="index"),
    path("categories",views.categories,name="categories"),
    path("send_celery_mail",views.send_celery_mail,name="send_celery_mail"),
    path("create-contest/<int:id>",views.create_contest,name="create_contest"),
    path("browse-contests", views.browse_contests, name="browse_contests"),
    path('create-contest/<str:contest>/<str:step>/',views.contest_step,name="contest_step"),
    path('edit-contest/<str:contest>/<str:step>/',contest_views.edit_contest,name="edit_contest"),
    path('edit-bc-contest/<str:contest>/<str:step>/',contest_views.bc_edit_contest,name="bc_edit_contest"),
    path('edit-wp-contest/<str:contest>/<str:step>/',contest_views.wp_edit_contest,name="wp_edit_contest"),
    path('edit-ba-contest/<str:contest>/<str:step>/',contest_views.ba_edit_contest,name="ba_edit_contest"),
    path('edit-et-contest/<str:contest>/<str:step>/',contest_views.et_edit_contest,name="et_edit_contest"),
    path('edit-sm-contest/<str:contest>/<str:step>/',contest_views.sm_edit_contest,name="sm_edit_contest"),
    path('edit-cn-contest/<str:contest>/<str:step>/',contest_views.cn_edit_contest,name="cn_edit_contest"),
    path('edit-ma-contest/<str:contest>/<str:step>/',contest_views.ma_edit_contest,name="ma_edit_contest"),
    path('edit-lp-contest/<str:contest>/<str:step>/',contest_views.lp_edit_contest,name="lp_edit_contest"),
    path('edit-td-contest/<str:contest>/<str:step>/',contest_views.td_edit_contest,name="td_edit_contest"),
    path('edit-md-contest/<str:contest>/<str:step>/',contest_views.md_edit_contest,name="md_edit_contest"),
    path('edit-bkc-contest/<str:contest>/<str:step>/',contest_views.bkc_edit_contest,name="bkc_edit_contest"),
    path('edit-mgc-contest/<str:contest>/<str:step>/',contest_views.mgc_edit_contest,name="mgc_edit_contest"),
    path('edit-wpd-contest/<str:contest>/<str:step>/',contest_views.wpd_edit_contest,name="wpd_edit_contest"),
    path('submit-contest/<str:contest>',views.submit_contest,name="submit_contest"),
    path('add-attachment/<str:contest>',views.add_attachment,name="add_attachment"),
    path('apply-discount/<str:contest>',views.apply_discount,name="apply_discount"),
    path('delete-attachment/<str:attach_id>',views.delete_attachment,name="delete_attachment"),
    path('draft-contest/<str:contest>',views.draft_contest,name="draft_contest"),
    path('decline-entry/<int:contest>/<int:entry>',views.decline_entry,name="decline_entry"),
    path('rate-entry/<int:contest>/<int:entry>',views.rate_entry,name="rate_entry"),
    path('confirm-finalists/<int:contest_id>',views.confirm_finalists,name="confirm_finalists"),
    path('confirm-winner/<int:contest_id>',views.confirm_winner,name="confirm_winner"),
    path('delete-contest/<int:contest_id>',contest_views.delete_contest,name="delete_contest"),
    path('add-announcement/<int:contest_id>',views.add_anouncement,name="add_anouns"),
    path('delete-announcement/<int:anouns_id>',views.delete_announcement,name="delete_anouns"),
    path('split-prize/<int:contest>',views.split_prize,name="split_prize"),
    path('split-prize-to-designers/<int:contest>',views.split_prize_to_designers,name="split_prize_to_designers"),
    path('invoice/<int:invoice>',views.invoice,name="invoice"),
    path('start_poll/<int:contest>',views.start_poll,name="start_poll"),
    path('poll/<int:poll>/edit',views.edit_poll,name="edit_poll"),
    path('poll/<poll>',views.poll_detail,name="poll_detail"),
    path('poll/<int:poll>/delete',views.delete_poll,name="delete_poll"),
    path('poll_obj/<int:poll_obj>/add_comment',views.add_poll_comment,name="add_poll_comment"),
    path('poll_obj/<int:poll_comment>/delete_comment',views.delete_comment,name="delete_comment"),
    path('teams',views.teams,name="teams"),
    path('invite-designer/<str:user>/<int:contest>',views.invite_designer,name="invite_designer")

]

home/urls.py
from django.urls import path, include
from home import views
from user import views as user_views

app_name = "home"

urlpatterns=[
    path("",views.index,name="index"),
    path("react",views.react,name="react"),
    path("get_by_filter", views.get_by_filter, name="get_by_filter"),
    path("contest/<int:contest_id>",views.contest,name="contest"),
    path("contest/<int:contest_id>/apply_filters",views.apply_filters,name="apply_filters"),
    path("entry/<int:contest_id>/<int:entry_id>",views.entry_detail,name="entry_detail"),
    path("add_comment/<int:contest_id>/<int:entry_id>",views.add_comment,name="add_comment"),
    path("delete_comment/<int:comment_id>",views.delete_comment,name="delete_comment"),
    path("edit_comment/<int:comment_id>",views.edit_comment,name="edit_comment"),
    path("create-payout-request/<str:user>",views.create_payout_request,name="create_payout_request"),
    path("nda/<int:contest_id>",views.nda,name="nda"),
    path("notifications/",views.notifications,name="notifications"),
    path("read_notifications/",views.read_notifications,name="read_notifications"),
    path("check_notifications/",views.check_notifications,name="check_notifications"),
    path("get_nots_list/",views.get_nots_list,name="get_nots_list"),
    path("submit-a-request/",views.submit_request,name="submit_request"),
    path("terms-of-use/",views.terms,name="terms"),
    path("privacy-policy/",views.privacy,name="privacy"),
    path("wallet/",views.wallet,name="wallet"),
    path('review/delete/<int:id>',views.delete_review,name="delete_review"),

    path("profile/<str:username>",user_views.public_profile,name="public_profile"),
    path("profile/<str:username>/about",user_views.profile_about,name="profile_about"),
    path('ref/<str:link>',views.refferal_link,name="refferal_link"),
    path('discover',views.discover,name="discover"),
    path('search',views.find_a_designer,name="find_a_designer"),





]

templates/customer/sm_contest_steps/edit/step_1.html
{% extends "customer/layout.html" %}
{% load static %}


{% block fa %}
<script src="https://kit.fontawesome.com/de7fd70cb4.js" crossorigin="anonymous"></script>    {% endblock %}
{% block head %}
    <title>Edit Contest / Zignative Crowdsourcing</title>
    <style>

    </style>
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <ol class="breadcrumb  mb-4 mt-2">
            <li class="breadcrumb-item "><a href="{% url "customer:categories" %}" class="step-link">Categories</a></li>
            <li class="breadcrumb-item active">Edit Contest</li>
        </ol>
        <h3 class="text-center mb-4">Edit Contest</h3>
        <div class="row  ">


            {% block step %}

                <div class="col-lg-3 ">

                    <div class="col-lg-10 mt-2 link-arrow">1. Brief</div>
                    <div class="col-lg-10 mt-2 ">

                        <a class="step-link" href="{% url "customer:sm_edit_contest" contest "step_2" %}">2. Style</a>
                    </div>


                </div>
                <div class="col-lg-7 ">
                    <h5>Name & Description</h5>
                    <div class="form-group">
                        <label for="contest-title">Contest Title</label>
                        <input required type="text" id="contest_title" onkeyup="setDraft(this)"
                               class="form-control">
                    </div>


                    <div class="form-group">
                        <label for="contest_detail">Tell us about your organization and your target audience
                            is</label>
                        <textarea required type="text" id="contest_detail" onkeyup="setDraft(this)"
                                  class="form-control"></textarea>
                    </div>

                       <br>

                    <h5 class="mt-3">Which social networks will you use?</h5>
                    <span class="" id="">Select all that apply.</span>
                    <span class="text-danger" id="warn_logo" style="visibility: hidden">Please choose at least 1 social network</span>
                    <div class="row mb-3 justify-content-center">

                        <div id="Facebook"
                             class="col-lg-3 logo-element socialmedia  pt-4 d-flex justify-content-center mr-2 mt-2">
                            <div style="width:150px; height:150px" class="text-center">
                                <h3 style="font-family: Arial, Helvetica, sans-serif;"><b><i class="fa fa-facebook-square fa-3x"></i></b></h3>
                                <h4 class="text-muted">Facebook</h4>
                            </div>
                        </div>
                        <div id="Twitter"
                             class="col-lg-3 logo-element socialmedia  pt-4 d-flex justify-content-center mr-2 mt-2">
                            <div style="width:150px; height:150px" class="text-center">
                                <h3 style="font-family: Arial, Helvetica, sans-serif;"><b><i class="fa fa-twitter-square fa-3x"></i></b></h3>
                                <h4 class="text-muted">Twitter</h4>
                            </div>
                        </div>
                        <div id="Instagram"
                             class="col-lg-3 logo-element socialmedia  pt-4 d-flex justify-content-center mr-2 mt-2">
                            <div style="width:150px; height:150px" class="text-center">
                                <h3 style="font-family: Arial, Helvetica, sans-serif;"><i class="fa fa-instagram fa-3x"></i></h3>
                                <h4 class="text-muted">Instagram</h4>
                            </div>
                        </div>
                        <div id="Youtube"
                             class="col-lg-3 logo-element socialmedia  pt-4 d-flex justify-content-center mr-2 mt-2">
                            <div style="width:150px; height:150px" class="text-center">
                                <h3 style="font-family: Arial, Helvetica, sans-serif;"><b><i class="fa fa-youtube-play fa-3x"></i></b></h3>
                                <h4 class="text-muted">Youtube</h4>
                            </div>
                        </div>
                        <div id="Pinterest"
                             class="col-lg-3 logo-element socialmedia  pt-4 d-flex justify-content-center mr-2 mt-2">
                            <div style="width:150px; height:150px" class="text-center">
                                <h3 style="font-family: Arial, Helvetica, sans-serif;"><i class="fa fa-pinterest fa-3x"></i></h3>
                                <h4 class="text-muted">Pinterest</h4>
                            </div>
                        </div>
                        <div id="Snapchat"
                             class="col-lg-3 logo-element socialmedia  pt-4 d-flex justify-content-center mr-2 mt-2">
                            <div style="width:150px; height:150px" class="text-center">
                                <h3 style="font-family: Arial, Helvetica, sans-serif;"><i class="fa fa-snapchat-square fa-3x"></i></h3>
                                <h4 class="text-muted">Snapchat</h4>
                            </div>
                        </div>
                        <div id="Linkedin"
                             class="col-lg-3 logo-element socialmedia  pt-4 d-flex justify-content-center mr-2 mt-2">
                            <div style="width:150px; height:150px" class="text-center">
                                <h3 style="font-family: Arial, Helvetica, sans-serif;"><i class="fa fa-linkedin fa-3x"></i></h3>
                                <h4 class="text-muted">Linkedin</h4>
                            </div>
                        </div>

                        <div id="Other"
                             class="col-lg-3 logo-element socialmedia  pt-5 d-flex justify-content-center mr-2 mt-2">
                            <div style="width:150px; height:150px" class="text-center">
                                <h3 style="font-family: Arial, Helvetica, sans-serif;"><i class="fa fa-question fa-2x"></i></h3>
                                <h4 class="text-muted">Other</h4>
                            </div>
                        </div>


                    </div>
                    <br>

                    <h5 class="mt-2">Industry</h5>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Please select your industry:</label>
                        <select required class="form-control" onchange="setDraft(this)" id="contest_industry">
                            <option value="">Industry</option>
                            <option>Accounting</option>
                            <option>Automotive</option>
                            <option>Beauty</option>
                            <option>Construction</option>
                            <option>Consulting</option>
                            <option>Dental</option>
                            <option>Education</option>
                            <option>Entertainment</option>
                            <option>Events</option>
                            <option>Financial</option>
                            <option>Home & Garden</option>
                            <option>Insurance</option>
                            <option>Internet</option>
                            <option>Legal</option>
                            <option>Manufacturing & Wholesale</option>
                            <option>Media</option>
                            <option>Medical</option>
                            <option>Miscellaneous</option>
                            <option>Natural Resources</option>
                            <option>Non-Profit</option>
                            <option>Real Estate</option>
                            <option>Religious</option>
                            <option>Restaurant</option>
                            <option>Retail</option>
                            <option>Service Industries</option>
                            <option>Sport</option>
                            <option>Technology</option>
                            <option>Travel & Hospitality</option>

                        </select>
                    </div>
                    <br>
                    <h5 class="mt-2">Do you want to provide any additional info?</h5>
                    <div class="form-group">
                        <label for="contest_detail">Are there specific design elements you want to see? Is there
                            anything
                            you do not want to see? Include links to things that inspired you, competitor information,
                            or
                            any other info. If you need special file formats, please list them here.</label>
                        <textarea  type="text" id="contest_info" onkeyup="setDraft(this)"
                                  class="form-control"></textarea>
                    </div>
                    <br>
                    <button onclick="nextStep()" type="submit" class="btn btn-primary float-right btn-lg mb-5 btn-block">
                        Next
                    </button>

                </div>
            {% endblock %}
        </div>
    </div>



{% endblock %}

{% block script %}
    {{ form_fields|json_script:"form_fields" }}

    {{ contest|json_script:"contest_id" }}
    <script src="{% static "dashboard/js/start_contest.js" %}"></script>
    <script>
        document.onload = fillData()
        var page_in = 0
        const datas = JSON.parse(localStorage.getItem(contest_id))

        if (datas !== null) {
            if ("filled_steps" in datas) {
                if (datas.filled_steps.includes("step_2") && !datas.filled_steps.includes("step_3")) {
                    document.getElementById("nondraft").classList.remove("text-muted")
                    document.getElementById("nondraft").innerHTML = `<a class="step-link" href="{% url "customer:contest_step" contest "step_2" %}">2. Style</a>
`
                }
            } else {
                datas.filled_steps = ["step_1"]
                storageStuff("filled_steps", datas.filled_steps)
            }
        } else {
            storageStuff("filled_steps", ["step_1"])
        }

        function verOdunu() {
            if (localStorage.getItem(contest_id)) {
                const contest = JSON.parse(localStorage.getItem(contest_id))

                postData('{% comment %}{% url "customer:draft_contest" contest %}{% endcomment %}', {"contest": contest})
                    .then(data => {
                        {#console.log(data); // JSON data parsed by `data.json()` call#}
                    });
            } else {
            }
        }

        verOdunu()
        if (localStorage.getItem(contest_id)) {
            const logos = document.getElementsByClassName("logo-element")
            const datas = JSON.parse(localStorage.getItem(contest_id))
            if (datas.selected_socialmedia) {


                Array.from(logos).forEach(
                    function (element, index, array) {
                        if (datas.selected_socialmedia.includes(element.id)) {
                            element.classList.add("logo-selected")
                            selected_logos.push(element.id)
                        }
                    })
            }
        }

        function save_as_draft() {
            if (localStorage.getItem(contest_id)) {
                storageStuff("page", "step_5")

                const contest = JSON.parse(localStorage.getItem(contest_id))
                postData('{% url "customer:draft_contest" contest  %}', {"contest": contest})
                    .then(data => {
                        console.log(data);
                    });
            } else {
            }
        }

        function nextStep() {
            save_as_draft()
            window.location = "{% url "customer:sm_edit_contest" contest "step_2" %}"

        }
    </script>

{% endblock %}

templates/customer/sm_contest_steps/edit/step_2.html
{% extends "customer/sm_contest_steps/edit/step_1.html" %}
{% load static %}
{% block head %}
    <style>
    .btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}

#img-upload{
    width: 100%;
}
    </style>

{% endblock %}
{% block step %}

        <div class="col-lg-3 ">

        <div class="col-lg-10 mt-2 "><a class="step-link" href="{% url "customer:sm_edit_contest" contest "step_1" %}">1. Brief</a></div>
            <div class="col-lg-10 mt-2 link-arrow">
            2. Style

        </div>



    </div>
    <div class="col-lg-9 ">
        <div class="row">
        <div class="col-9 mt-3">

                <h5>Add attachment </h5>
            <div id="attachment-list">
            {% for attachment in attachments %}
            <div class="border mt-4 mb-4">
              <div class="row m-1 ">

                   <div class="col-2 p-3">

                      <img src="{{attachment.get_image}}" class="img-responsive border pre-im" width="120" height="120" alt="">

                  </div>
                  <div class="col-10 pt-3 pb-3 pl-3">
                      <div class="border p-3" style="max-height:150px;height:100%;overflow-y:auto">
                          <div class="float-right" style="display:inline">
                              <a style="cursor:pointer" url="{% url "customer:delete_attachment" attachment.id %}" onclick="are_u_sure_for_delete(this)" class="step-link">
                                  <span><i class="fa fa-trash"></i></span>
                              </a>
                          </div>



                          {{ attachment.content }}

                      </div>
                  </div>


              </div>
            </div>
            {% endfor %}

            </div>


            <div class="border mt-4 mb-4">
            <form  class="attachment-form" enctype="multipart/form-data" >
              <div class="row m-2 ">
                   <div class="col-2 p-3">

                      <img id="image_img" src="{% static "dashboard/images/add-image.png" %}" class="img-responsive border pre-im" width="120" height="120" alt="">
                      <span class="btn btn-light col-12 text-center btn-sm btn-file">
                        Browse… <input id="image_input" required type="file" name="image" class="im-up" onchange="im_upload(this)">
                        </span>
                  </div>
                  <div class="col-10 p-3">
                      <label for="" style="display:none;"></label><textarea id="detail_txt" required placeholder="Detail your attachment" name="detail" class="form-control" id="" style="height:100%"></textarea>

                  </div>
                  <button type="submit"  class="btn btn-success float-right  btn-block">Add</button>

              </div>
            </form>
            </div>



        </div>
    </div>
        <h5 class="mt-3">Which fonts do you prefer?</h5>
        <span class="text-danger" id="warn_logo" style="visibility: hidden">Please choose at least 1 font</span>
        <div class="row mb-3">

                <div id="sans_serif" class="col-lg-3 logo-element font pt-4 d-flex justify-content-center mr-2 mt-2">
                    <div style="width:150px; height:150px"  class="text-center">
                    <h1 style="font-family: Arial, Helvetica, sans-serif; font-size:72px"><b>Aa</b></h1>
                    <h4>Sans-Serif</h4>
                    </div>
                </div>
                <div id="serif" class="col-lg-3 logo-element font pt-4 d-flex justify-content-center mr-2 mt-2">
                    <div style="width:150px; height:150px"  class="text-center">
                    <h1 style="font-family:  serif; font-size:72px">Aa</h1>
                    <h4>Serif</h4>
                    </div>
                </div>
                <div id="block_serif" class="col-lg-3 logo-element font pt-4 d-flex justify-content-center mr-2 mt-2">
                    <div style="width:150px; height:150px"  class="text-center">
                    <h1 style="font-family: 'Roboto Slab'; font-size:72px">Aa</h1>
                    <h4>Block Serif</h4>
                    </div>
                </div>
                <div id="script" class="col-lg-3 logo-element font pt-4 d-flex justify-content-center mr-2 mt-2">
                    <div style="width:150px; height:150px"  class="text-center">
                    <h1 style="font-family: 'Freestyle Script'; font-size:72px">Aa</h1>
                    <h4>Script</h4>
                    </div>
                </div>
                <div id="mono" class="col-lg-3 logo-element font pt-4 d-flex justify-content-center mr-2 mt-2">
                    <div style="width:150px; height:150px"  class="text-center">
                    <h1 style="font-family: monospace; font-weight: lighter; font-size:72px">Aa</h1>
                    <h4>Mono</h4>
                    </div>
                </div>
                <div id="no_preference" class="col-lg-3 logo-element font pt-4 d-flex justify-content-center mr-2 mt-2">
                    <div style="width:150px; height:150px"  class="text-center">
                    <h1 style="font-family: monospace; font-weight: lighter; font-size:72px"><i class="fa fa-question-circle"></i></h1>
                    <h4>No preference</h4>
                    </div>
                </div>

                <button onclick="nextStep()" class="btn btn-primary float-right btn-lg col-lg-9 btn-block mt-5">Save</button>

        </div>


    </div>
{% endblock %}
{% block script %}
    {{ form_fields|json_script:"form_fields"}}

    {{ contest|json_script:"contest_id" }}
    <script src="{% static "dashboard/js/start_contest.js" %}"></script>
    <script>
            const request = new Request()

         var datas = JSON.parse(localStorage.getItem(contest_id))
         var steps=datas.filled_steps
         if (!steps.includes("step_2")){
             steps.push("step_2")
         }
         storageStuff("filled_steps",steps)
         document.onload = fillData()

        if (localStorage.getItem(contest_id)) {
            const logos = document.getElementsByClassName("logo-element")
            const datas = JSON.parse(localStorage.getItem(contest_id))
            if (datas.selected_fonts) {


                Array.from(logos).forEach(
                    function (element, index, array) {
                        if (datas.selected_fonts.includes(element.id)) {
                            element.classList.add("logo-selected")
                            selected_logos.push(element.id)
                        }
                    })
            }
        }

        function control(){
            if(selected_logos.length >= 1){
                window.location="{% url "customer:contest_step" contest "step_3" %}"
            }else{
                document.getElementById("warn_logo").style.visibility=""
            }
        }
        function save_as_draft() {
            if (localStorage.getItem(contest_id)) {
                const contest = JSON.parse(localStorage.getItem(contest_id))

                postData('{% url "customer:draft_contest" contest  %}', {"contest": contest})
                    .then(data => {
                        window.location="{% url "home:contest" contest  %}"
                    });
            } else {
            }
        }

            function nextStep() {
                save_as_draft()


            }


          const im_upload = imgInp => {

          const [file] = imgInp.files
          var blah = imgInp.parentElement.parentElement.getElementsByTagName('img')[0]

          if (file) {
            blah.src = URL.createObjectURL(file)
          }
        }


         var forms = document.getElementsByClassName("attachment-form")

        for (var i = 0; i < forms.length; i++) {
            forms[i].addEventListener("submit",attachEvent)
        }
        const toBase64 = file => new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = () => resolve(reader.result);
            reader.onerror = error => reject(error);
        });

        async function upload(file,detail) {
            var list_html = document.getElementById("attachment-list")
            var image = document.getElementById("image_img")
            var image_input = document.getElementById("image_input")
            var text = document.getElementById("detail_txt")

            var attach = {
                img:await toBase64(file),
                detail:detail
            }

            request.post("{% url 'customer:add_attachment' contest  %}", attach

            , csrftoken)
            .then(data => {
                list_html.innerHTML += data.attachment
                image.src = "{% static "dashboard/images/add-image.png" %}"
                image_input.value = ''
                text.value = ''

            })
            .catch(err => alert("Something went wrong."));

        }



         function attachEvent(e){
            var img = e.target.elements.image.files[0];
            var detail = e.target.elements.detail.value;


            upload(img,detail)

            e.preventDefault()
         }

         function are_u_sure_for_delete(el) {
        var url=el.getAttribute("url")
       if (confirm("Are you sure to delete this attachment?")){
           window.location=url
       }else{
       }
    }
    </script>
{% endblock %}